version: "3.9"

services:
  vm-mini:
    build: .
    ports:
      - "3100:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./db:/app/db
    restart: unless-stopped